title: "J. LÓPEZ M. - Escritor Nicaragüense"
description: "Página oficial del escritor J. LÓPEZ M. - Autor de Nacen Los Hermanos"
baseurl: ""
url: "https://javierlm71.github.io"
theme: null
plugins: []
include: [".nojekyll"]
